app:
  name: my-app
  replicaCount: 2

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

database:
  name: my-database
  username: {{ .Values.db.username }}
  password: {{ .Values.db.password }}
  host: mysql
  port: 3306

db:
  username: dbuser
  password: dbpassword
  rootPassword: rootpassword

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: myapp.local
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
