apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-helm-chart.fullname" . }}-nginx-health-config
  labels:
    {{- include "my-helm-chart.labels" . | nindent 4 }}
data:
  health: |
    <html>
    <body>
      <h1>Health Check OK</h1>
    </body>
    </html>
  ready: |
    <html>
    <body>
      <h1>Ready Check OK</h1>
    </body>
    </html>

