apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-health-config
  namespace: app-namespace
data:
  health: |
    <html>
    <body>
      <h1>Health Check OK</h1>
    </body>
    </html>
  ready: |
    <html>
    <body>
      <h1>Ready Check OK</h1>
    </body>
    </html>
