apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: app-namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:  # Eliminado el campo host para permitir acceso directo por IP
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-service  # Nombre del servicio que se está exponiendo
                port:
                  number: 80  # Puerto del servicio

  