apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: db-namespace
type: Opaque
data:
  mysql-root-password: bXlzcWwtcm9vdC1wYXNzd29yZA== # Base64 de 'test-pass'
  mysql-user: bXlzcWwtdXNlcg== # Base64 de 'username'
  mysql-password: bXlzcWwtcGFzc3dvcmQ= # Base64 de 'password'




apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: app-namespace
type: Opaque
data:
  db-username: ZGItdXNlcm5hbWU=  # Tu usuario de base de datos
  db-password: ZGItcGFzc3dvcmQ=  # Tu contraseña de base de datos
  
  