apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-helm-chart.fullname" . }}-secret
  labels:
    {{- include "my-helm-chart.labels" . | nindent 4 }}
type: Opaque
data:
  # Credenciales de la base de datos (db-secret)
  mysql-root-password: {{ .Values.mariadb.auth.rootPassword | b64enc }}
  mysql-user: {{ .Values.mariadb.auth.user | b64enc }}
  mysql-password: {{ .Values.mariadb.auth.password | b64enc }}
  mysql-database: {{ .Values.mariadb.auth.database | b64enc }}

  # Credenciales de la aplicación (app-secret)
  db-username: {{ .Values.app.db.username | b64enc }}
  db-password: {{ .Values.app.db.password | b64enc }}

  
  