apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: db-namespace
spec:
  selector:
    app: db-app
  ports:
    - port: 3306
  clusterIP: None
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: app-namespace
spec:
  type: ClusterIP
  selector:
    app: my-app
  ports:
    - port: 80
      targetPort: 80

